# Generated by Django 5.1.1 on 2024-11-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', 'add_vector_extension'),
    ]

    operations = [
    ]
