# Generated by Django 5.1.1 on 2024-10-06 22:52

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_alter_photo_user_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=photos.models.user_directory_path),
        ),
    ]
