# Generated by Django 5.1.1 on 2024-10-06 23:12

import photos.models
import photos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                storage=photos.storage.UserS3Storage,
                upload_to=photos.models.user_directory_path,
            ),
        ),
    ]
